services:

  postgres:
    image: postgres:17
    container_name: springmart-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

  redis:
    image: redis:8
    container_name: springmart_redis

    command: redis-server --appendonly yes

    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    restart: unless-stopped

  app:
    build: .
    container_name: springmart-app

    environment:
      SpringMart_DB_URL: ${SpringMart_DB_URL_DOCKER}
      SpringMart_DB_USERNAME: ${SpringMart_DB_USERNAME}
      SpringMart_DB_PASSWORD: ${SpringMart_DB_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    ports:
      - "8080:8080"

    restart: unless-stopped


volumes:
  postgres_data:
  redis_data: